---
openapi: 3.0.0
info:
  title: NBA2021 
  description: Api For Chatbot
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /search:
    get:
      tags:
      - developers
      summary: For chatbot 
      description: For chatbot
      operationId: search 
      parameters:
        - in: query
          name: q 
          schema:
            type: string 
          description: the string to be searched
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NBASearch.Arn}/invocations'
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: when_no_match
        httpMethod: POST #always POST
        type: aws_proxy
      responses:
        "200":
          description: Search 
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        "400":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    SearchResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/Data'
    Data:
      type: object
      properties:
        url:
          type: string
        labels:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
