swagger: '2.0'
info:
  title: NBA Upload Player Photo
  description: 'NBA Upload API'
  version: 1.0.0
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /upload:
    post:
      summary: Upload photos to S3 bucket to trigger lambda.
      description: |
        This API helps to upload a photo to S3 bucket, and then return the a json value from lambda.
      operationId: sendMessage
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UploadRequest'
      responses:
        '200':
          description: Response from lambda
          schema:
            $ref: '#/definitions/UploadResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  UploadRequest:
    type: object
    properties:
      bucket:
        type: string
      photoname:
        type: string
  UploadResponse:
    type: object
    properties:
      results:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string